language: cpp
sudo: false
matrix:
  include:
    - os: linux
      compiler: gcc-6
      script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_CXX_COMPILER=g++-6 -DCMAKE_C_COMPILER=gcc-6 ../
        - make -j 2
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - xorg-dev
            - libglu1-mesa-dev
            - g++-6
            - gcc-6
            - cmake
            - cmake-data
            - libblas-dev
            - liblapack-dev
    #         - binutils
    #         - libx11-dev
    #         - mesa-common-dev
    #         - libgl1-mesa-dev
    #         - libglu1-mesa-dev
    #         - libxrandr-dev
    #         - libxi-dev
    #         - libxmu-dev
    #         - libblas-dev
    #         - xorg-dev
    - os: osx
      compiler: clang
      script:
        # - brew update
        # - brew upgrade cmake
        # - brew upgrade cgal
        - mkdir build
        - cd build
        - cmake ../
        - make -j 2
